apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-push-run
  namespace: hor
spec:
  serviceAccountName: build-sa
  taskRef:
    name: build-and-push
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: cjx-res
